Version 5.2.1

diff --git a/PythonInterface/Dockerfile.manylinux b/PythonInterface/Dockerfile.manylinux
--- a/PythonInterface/Dockerfile.manylinux
+++ b/PythonInterface/Dockerfile.manylinux
@@ -97,7 +97,15 @@ RUN /opt/python/cp312-cp312/bin/pip wheel .
 # Repair wheels using auditwheel
 RUN mkdir /wheels
 ENV LD_LIBRARY_PATH=/src/PythonInterface/dplus
-RUN find . -name "dplus_api*whl" -exec auditwheel repair {} -w /wheels \;
+RUN for whl in /src/PythonInterface/dplus_api*.whl; do \
+    echo "Repairing: $whl"; \
+    auditwheel repair "$whl" -w /wheels || echo "auditwheel failed for $whl"; \
+done
+# RUN find . -name "dplus_api*whl" -exec auditwheel repair {} -w /wheels \;
 
 # MODIFIED ENTRYPOINT
-ENTRYPOINT [ "cp", "-r", "/wheels/.", "/external/dplus-api-wheels/"]
+# ENTRYPOINT [ "cp", "-r", "/wheels/.", "/external/dplus-api-wheels/"]
+#CMD ["bash", "-c", "mkdir -p /external/dplus-api-wheels && cp -v /wheels/* /external/dplus-api-wheels/"]
+CMD ["bash", "-c", "mkdir -p /external/dplus-api-wheels && cp -v /wheels/* /external/dplus-api-wheels/ || cp -v /src/PythonInterface/dplus_api*.whl /external/dplus-api-wheels/"]
+
+
